### PR TITLE
A proposal for redesigning anon-connection-wizard for better usability 

### PR DESCRIPTION
**Pull request by irykoon**
# Background
Currently, I have been working on the anon-connection-wizard, a Python-clone of the Tor Launcher which aims at providing Tor users with a graphical instruction on configuring the Tor. The application is especially helpful for users who live in Tor-censored area. This is because those users can only connect to the Tor network with the help of other censorship circumvention tools which include but are not limited to Tor bridges, pluggable transports and other third party Internet censorship circumvention tools like Lantern and VPN. 

# Problem Statement
However, the current instruction provided by the anon-connection-wizard and Tor launcher may not be clear enough. That is to say, users are very likely to not be able to correctly connect to the Tor network even with the help of their instruction. 

# Related Research
A detailed and published [research](https://www2.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-58.pdf) conducted in 2015 also addressed the problem [1]. In that research, the researchers firstly did a small-scale user behavior experiment on the Tor Launcher for Tor Browser Bundle 5.0.3. And then, they redesigned the user interface of it basing on their observation on users’ behaviors and the direct feedback from the users. After finishing the redesign of the Tor launcher, they conducted a 124-participant experiment which aimed at examining the effectiveness of their redesign. The result showed an approximately 10 percentages of improvement in success rate  and a 100 percentages of reducing on the time to success when comparing their redesign of Tor Launcher with the original one. For reasons I do not know, their [redesigned Tor Launcher](https://github.com/nmalkin/tor-launcher) [2] has not been adopted by the Tor project. However, since anon-connection-wizard is a clone of the Tor Launcher, it may be able to benefit from the recommendations and suggestions offered by that research. 

# Other Improvement
If you believe the redesign of the anon-connection-wizard is a good idea, I also have some other recommendations. The current Tor Launcher mainly focuses on helping users circumvent the Internet censorship by Tor-supported methods like bridges and obfuscation technology. However, in areas under strict censorship, those methods may not be sufficient to help users to circumvent the Internet censorship. For example, in countries like China, the [only](https://www.torproject.org/docs/pluggable-transports) usable Tor-supported censorship circumvention method is “meek-amazon” [3], which also does not grantee working all the time. Besides, meek has not been [supported](https://phabricator.whonix.org/T386 ) by Whonix yet [4], making people in China or other heavily-censored area hard to connect to Tor only with the help of those Tor-supported censorship circumvention methods. In fact, people in those area usually use some third-party censorship circumvention tools to connect to the Tor network. Two main options are Virtual Private Network and proxy-based censorship circumvention tools like Psiphon3 and Lantern. 
Unfortunately, the Tor Launcher and the current anon-connection-wizard have not provided users using those third-party censorship circumvention tools with sufficient instructions. To clarify the problem, the following two examples simulate those users’ experience:
1. Alice uses a VPN to bypass the Internet censorship. One day she wants to try using the Tor. The first question asked by anon-connection-wizard is to describe her situation. Although knowledgeable users know she can connect to the Tor network “directly” using that VPN, Alice, as a first-time user may find “This computer’s Internet connection is censored” described her situation better.
2. Similarly, Bob uses the Lantern software to connect to the free Internet. One day he wants to try using the Tor. After choosing the configure option, Bob is asked if he’s connection to the Tor-network is censored. Naturally, Bob answers yes to that question and then he is asked to configure bridges in order to connect to the Tor network. After finishing that step, he is asked if he needs a proxy to connect to the Internet. Of course Bob does not think he needs one because he just checked the weather on the Internet without even knowing what proxy is. However, we know that the bridges will not be very helpful for Bob and all he has to do is to set proxy to use Lantern. What’s even worse? Even if Bob knows he does not need a bridge but a proxy setting to connect to the Tor network, the next step is still not easy for him. Since every time the proxy setting is auto-configured by Lantern client, Bob even does not know which port Lantern is listening on. Bob also does not know what is the proxy IP of Lantern. Bob does not know what 127.0.0.1 or local-host means. Bob is not sure if he needs an username and a password for his proxy. All the confusing questions make Bob frustrated. With the last hope, Bob tries to visit the URL provided by the anon-connection-wizard for help. But this does not work neither because the Tor website is also blocked.

# Alternative Choice
The two examples above illustrates how confusing the current instructions in anon-connection-wizard is. However, one may argue that we can use an online documents to instruct users how to configure it correctly instead of redesigning the anon-connection-wizard. Although I agree that an online documentation can be helpful to users, I do not think it can replace the redesign of the anon-connection-wizard because it makes anon-connection-wizard meaningless. Beside the potential connection issue to the online documents, if a large amount of users have to see online documents to configure anon-connection-wizard, they can see an online guideline on how to configure the torrc file manually instead.

# My Position
According to the argument above, I would like to propose a redesign of the current anon-connection-wizard which aims at improving its usability. I hope that my work will help more people to connect to the Tor network efficiently and successfully.

# Research Schedule
My planning research schedule is as follows:
1. Generate ideas on redesigning the anon-continence-wizard users interface, basing on the recommendations from outside sources, problems discussed above and suggestions from other people (11/March/2017-12/March/2017);
2. Present the planning redesign to public to receive feedback (12/March/2017);
3. Implement the redesign (12/March/2017-17/March/2017);
4. Prepare for the user behavior experiment, including recruitment and setting up environment  (18/March/2017-20/March/2017);
5. Conduct the experiment (21/March/2017);
6. Process and analysis the experiment data (22/March/2017-24/March/2017);
7. Write the research report (25/March/2017-29/March/2017).

# References
[1] Fifield, David et al. "Tor’S Usability For Censorship Circumvention". N.p., 2017. Web. 11 Mar. 2017.
[2] "Nmalkin/Tor-Launcher". GitHub. N.p., 2017. Web. 11 Mar. 2017. 
[3] The Tor Project, Inc. "Tor Project: Pluggable Transports". Torproject.org. N.p., 2017. Web. 11 Mar. 2017.
[4]  “T386 Meek Pluggable Transport". Phabricator.whonix.org. N.p., 2017. Web. 11 Mar. 2017.

### CODE REVIEW

**Comment by irykoon** [comment]
Could anyone offer me some feedback about the proposal above please?
Any recommendation, suggestion and criticism are very welcome!

**Comment by adrelanos** [comment]
I'll get back to this tomorrow.

irykoon:
> Could anyone offer me some feedback about the proposal above please?
> Any recommendation, suggestion and criticism are very welcome!

I guess not many people are being notified about items posted here. For
wider input, could you please post this on:

- tor-talk mailing list
- Whonix development forum
- qubes-devel mailing list?

**Comment by irykoon** [comment]
adrelanos:
>  could you please post this on: 
>- tor-talk mailing list 
>- Whonix development forum 
>- qubes-devel mailing list?

Thank you very much for your advice, Patrick! I have posted it on these three places.

**Comment by irykoon** [comment]
I have received a reply from the tor-talk mailing list, telling me that there was a [discussion](https://lists.torproject.org/pipermail/tbb-dev/2017-February/000473.html) on a similar proposal. 

Although it has exceeded the deadline (March 3rd) of giving feedback right now, I still sent an email to the tbb-dev mailing list. This is because problems mentioned in my proposal still exist in their [planning redesign](https://trac.torproject.org/projects/tor/attachment/wiki/doc/TorLauncherUX2016/NEW-interface.png). 

Related Tor docs can be found [here](https://trac.torproject.org/projects/tor/wiki/doc/TorLauncherUX2016#Designconsiderations).

**Comment by adrelanos** [comment]
irykoon:
> I have received a reply from the tor-talk mailing list, telling me
> that there was a
> [discussion](https://lists.torproject.org/pipermail/tbb-dev/2017-February/000473.html)
> on a similar proposal.

Right.

(Note, tor-launcher may very likely not work inside Whonix, since it
would be tied to Tor Browser without chance to sanely use it standalone.
Their usability research applies equally indeed.)

What you are working on may be also the solution for the following ticket:

https://trac.torproject.org/projects/tor/ticket/7197

> Although it has exceeded the deadline (March 3rd) of giving feedback
> right now, I still sent an email to the tbb-dev mailing list.

Sure thing. Please keep on jumping into any related discussion.

**Pull request merged**
